# Generated by Django 3.2.4 on 2021-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
