# Generated by Django 3.2.4 on 2021-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieprofile', '0002_alter_profilecustomer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileproducer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
